# Generated by Django 4.2.5 on 2023-10-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='tipo',
            new_name='equipo',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo_de_bateria',
            field=models.CharField(max_length=100),
        ),
    ]
